### ISSUE TITLE
Save names

### ISSUE THREAD

**Issue by Danthehedgefox** [nvllsvm/GZDoom-Android#18]
While a gamepad is connected you can only use the numbers on the touch keyboard.

**Comment by nvllsvm** [comment]
Please provide the following:
- Device manufacturer and model
- OS version (include custom ROM information if you're using one)
- App version
- Controller model

Also, if you're not using the stock keyboard of the ROM, please provide the name and version of the one you are using.

**Comment by Danthehedgefox** [comment]
Alcatel, AA466BG
6.0
0.2.1
Green Throttle Atlas

**Comment by Danthehedgefox** [comment]
I just checked, turns out I'm not able to use the letter keys at all, even when when a gamepad isn't connected.

**Comment by nvllsvm** [comment]
I'm not able to replicate.

**Comment by Danthehedgefox** [comment]
Oh well, I'll just deal with it, don't worry.

**Comment by nvllsvm** [comment]
Closing in favor of https://github.com/nvllsvm/GZDoom-Android/issues/21
