### ISSUE TITLE
build.sh cp error

### ISSUE THREAD

**Issue by HardSer** [nvllsvm/GZDoom-Android#31]
Hello!
When running build.sh, I see this:
cp: can't run stat for 'android_gzdoom/new/src/gl/data/gl_sections.cpp': No such file or directory
cp: can't run stat for 'android_gzdoom/new/src/gl/data/gl_sections.h': No such file or directory
Can it be fixed or this is just a warning and it won't crash build?

P.S: running on Xubuntu 17 x64

**Comment by nvllsvm** [comment]
Fixed https://github.com/nvllsvm/GZDoom-Android/commit/9693a748e2b016d423fe2bcc598dd4a86c1e913f
