### ISSUE TITLE
GZDoom version

### ISSUE THREAD

**Issue by Megaeloelo** [nvllsvm/GZDoom-Android#8]
What version of GZDoom this APP is using? 
And what happened to the compiled apk in release tab? 
Sorry for bad english.

**Comment by nvllsvm** [comment]
It's using a development release of GZDoom 2.1. I'm not able to pinpoint which exact commit it corresponds to in the GZDoom repo.

The app was removed since it was downloading music assets from Beloko's site. A new release is in the works.

**Comment by Megaeloelo** [comment]
Ok thx for the informations, but sadly mod that i'm using didnt work. It has bug that only happens on older version that gzdoom 2.1 That's strange O_o
Anyway, closing.
